name: Build and Push Custom Image

on:
  schedule:
    - cron: 0 12 */7 * *
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build-and-push.yml"
    branches:
      - main
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/build-and-push.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  SLUG: ${{ github.repository_owner }}/ubuntu

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive image version
        id: meta
        run: |
          echo IMAGE_VERSION=$(date -u +'v%y.%m.%d') | tee -a $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ env.SLUG }}:${{ steps.meta.outputs.IMAGE_VERSION }}
            ghcr.io/${{ env.SLUG }}:latest
          platforms: |
            linux/amd64
            linux/arm64